### ISSUE TITLE
Release checklist for sgrep

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#406]
Why: We need to communicate to our users sgrep changes.

Should include
- [x] Release instruction process
- [x] Version Controlled Changelog file
- [x] Standardized git commit messages
- [x] QA process
...

**Comment by brendongo** [comment]
We have a general release checklist and the github actions + scripts generally work. Will track bugs that popup from this as they pop up.
