### ISSUE TITLE
metavariable-regex meta-char escape inconsistency bug

### ISSUE THREAD

**Issue by dpnishant** [semgrep/semgrep#5321]
**Describe the bug**
As seen in the playground URL: https://semgrep.dev/playground/s/dpnishant:regex-escaping-bug I'm not able to match the literal `*` with a regex like `\*` in python language. However in the playground URL: https://semgrep.dev/playground/s/dpnishant:regex-escaping-bug-2, I have able to match the literal `*` using without escaping the `*` in the regex as shown in Kotlin language. Also the regex matcher throws error when left unescaped in a capturing group as seen in the playground URL: https://semgrep.dev/playground/s/dpnishant:regex-escaping-bug-3

**To Reproduce**
Use the following playground URLs
* https://semgrep.dev/playground/s/dpnishant:regex-escaping-bug
* https://semgrep.dev/playground/s/dpnishant:regex-escaping-bug-2
* https://semgrep.dev/playground/s/dpnishant:regex-escaping-bug-3

**Expected behavior**
The regex escaping syntax should be done with a preceding `\` character consistently across languages and all sections that accept regex patterns.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep 0.93.0 on macOS (via Homebrew)

**Use case**
Wider adoption with better coverage.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1386/metavariable-regex-meta-char-escape-inconsistency-bug. _Note_: this link is for r2c use only and is not accessible publicly.
