### ISSUE TITLE
--no-test-ignore-todo doesn't seem to work

### ISSUE THREAD

**Issue by yogaxpto** [semgrep/semgrep#5685]
**Describe the bug**
Tried to test a custom rule with `--no-test-ignore-todo doesn't seem to work` and it doesn't seem to work

**To Reproduce**
Tried on a docker image using the code from the [documentation](https://semgrep.dev/docs/writing-rules/testing-rules/#example):

```Dockerfile
FROM returntocorp/semgrep

RUN echo "rules:" > app.yaml
RUN echo "- id: insecure-eval-use" >> app.yaml
RUN echo "  patterns:" >> app.yaml
RUN echo "  - pattern: eval(...)" >> app.yaml
RUN echo "  - pattern-not: eval("...")" >> app.yaml
RUN echo "  message: Calling 'eval' with user input" >> app.yaml
RUN echo "  languages: [python]" >> app.yaml
RUN echo "  severity: WARNING" >> app.yaml

RUN echo "# todoruleid: insecure-eval-use" > app.py
RUN echo "totally_safe_eval(user_input)" >> app.py

ENTRYPOINT [ "semgrep" ]
CMD ["--quiet","--test", "--no-test-ignore-todo", "."]
```

**Expected behavior**
I expected semgrep to raise an error in this situation.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
Allow me to test semgrep rules with new examples marked with `todo`.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1605/no-test-ignore-todo-doesnt-seem-to-work. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by yogaxpto** [comment]
I don't think I can reopen this issue, but it still persists.
