### ISSUE TITLE
Reduce the amount of boilerplate to modify when changing AST type

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#6440]
**Is your feature request related to a problem? Please describe.**

I'm in the process of adding SQL constructs for the Apex language, which is a dialect of Java that supports embedded SQL statements. This requires extending the Java AST type and similarly extending Semgrep's generic AST. The two files containing new type definitions are:

* [ast_java.ml](https://github.com/returntocorp/pfff/blob/cadd266de3996c7da4bd08b82eba66a71bfec32d/lang_java/parsing/ast_java.ml)
* [AST_generic.ml](https://github.com/returntocorp/semgrep/blob/3333891939432f9c4fc7567d9da7d1d671c61a37/semgrep-core/src/core/ast/AST_generic.ml)

After modifying these types, I have to add boilerplate for traversing the tree in the following source files:

- [java_to_generic.ml](https://github.com/returntocorp/semgrep/blob/3333891939432f9c4fc7567d9da7d1d671c61a37/semgrep-core/src/parsing/pfff/java_to_generic.ml) &rarr; ?? (maps one tree type to another)
- [visitor_java.ml](https://github.com/returntocorp/pfff/blob/cadd266de3996c7da4bd08b82eba66a71bfec32d/lang_java/parsing/visitor_java.ml) &rarr; [ppx visitors](https://gitlab.inria.fr/fpottier/visitors)
- [graph_code_java.ml](https://github.com/returntocorp/pfff/blob/cadd266de3996c7da4bd08b82eba66a71bfec32d/lang_java/analyze/graph_code_java.ml) &rarr; ppx visitors
- [Map_AST.ml](https://github.com/returntocorp/semgrep/blob/3333891939432f9c4fc7567d9da7d1d671c61a37/semgrep-core/src/core/ast/Map_AST.ml) &rarr; ppx visitors
- [Meta_AST.ml](https://github.com/returntocorp/semgrep/blob/3333891939432f9c4fc7567d9da7d1d671c61a37/semgrep-core/src/core/ast/Meta_AST.ml) &rarr; [ppx deriving show](https://github.com/ocaml-ppx/ppx_deriving)
- [AST_generic_to_v0.ml](https://github.com/returntocorp/semgrep/blob/3333891939432f9c4fc7567d9da7d1d671c61a37/semgrep-core/src/experiments/api/AST_generic_to_v1.ml) &rarr; ?? (map from one tree type to another)
- [Visitor_AST.ml](https://github.com/returntocorp/semgrep/blob/3333891939432f9c4fc7567d9da7d1d671c61a37/semgrep-core/src/core/ast/Visitor_AST.ml) &rarr; ppx visitors
- [AST_to_SAST.ml](https://github.com/returntocorp/semgrep-proprietary/blob/d006d842f42d2f1d2ac8a38622dbad3c080a0139/src/core/sast/AST_to_SAST.ml) &rarr; ?? (map from one tree type to another)
- [AST_to_IL.ml](https://github.com/returntocorp/semgrep/blob/3333891939432f9c4fc7567d9da7d1d671c61a37/semgrep-core/src/analyzing/AST_to_IL.ml) &rarr; ?? (map from one tree type to another)
- [SubAST_generic.ml](https://github.com/returntocorp/semgrep/blob/3333891939432f9c4fc7567d9da7d1d671c61a37/semgrep-core/src/matching/SubAST_generic.ml) &rarr; ppx visitors (extracts expr nodes from tree)
- [Generic_vs_generic.ml](https://github.com/returntocorp/semgrep/blob/3333891939432f9c4fc7567d9da7d1d671c61a37/semgrep-core/src/matching/Generic_vs_generic.ml) &rarr; no obvious simplification
- [ast_generic_v1.atd](https://github.com/returntocorp/semgrep-interfaces/blob/72c007191c33555079c13db4e8791497920f7208/ast_generic_v1.atd) to be done later when we decide to publish v2 of the generic AST &rarr; copy-paste-edit OCaml type definitions from `AST_generic.ml`

That's 3 files for Java and 9 for the generic AST. Updating them by hand takes the best part of a day. Any revision made to the type definitions requires re-editing all those files accordingly. The code does nothing and the compiler checks everything, so it's safe but it's boring and wastes time.

**Describe the solution you'd like**

Subtasks:
- [x] use off-the-shelf ppx derivers for visitors (iter, map, fold) https://github.com/returntocorp/semgrep/issues/6450
- [ ] use off-the-shelf dumpers (ppx_deriving show) https://github.com/returntocorp/semgrep/issues/6451
- [x] modernize ocamltarzan or similar to make it easy to generate boilerplate code that can then be copy-pasted and edited, for all the cases where a simple solution doesn't already exist. https://github.com/returntocorp/semgrep/issues/6452
