### ISSUE TITLE
[scala] taint tracking not working as expected for Try/Catch

### ISSUE THREAD

**Issue by hamza-db** [semgrep/semgrep#8438]
**Describe the bug**
taint tracking is not working as expected when the try/catch statment is not followed by any other statements / code

**To Reproduce**
https://semgrep.dev/playground/s/Ney7

looks like there is an issue when looking at the cfg-il and comparing the working example vs the one not working :  
<img width="753" alt="semgrep-bug" src="https://github.com/returntocorp/semgrep/assets/112495782/5d6e3160-bb11-476b-b9cd-c253a27c49e4">

**Expected behavior**
Detect and track taint inside a Try block

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
give us more confidence in the results of taint tracking, and close a blind spot.

**Comment by IagoAbal** [comment]
This has been fixed!
